server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.112.187:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
